language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
env:
  global:
    secure: "WPYuGHi++I4+WBw/kJS3y11CJ1Qb3e98dw0Q+VgB1Da/0uX+LpCHWeE796aCdr+JrwJ6HHrrnhEoBs5bzkXw6j0UGanAUA7SGkNLcMsiKyyknxxOZ1fQ6Z5gZqGuFR+PZOcyRyciHzKwHVwn1A5RX4KPmiE58/UnPkqNR54ix+U="
